- name: Generation kubelet Kubernetes Configuration File
  shell: |
    kubectl config set-cluster kubernetes-the-hard-way \
      --certificate-authority=../ca.pem \
      --embed-certs=true \
      --server=https://{{ hostvars[groups['proxy'][0]].ansible_host }}:6443 \
      --kubeconfig={{ item }}.kubeconfig

    kubectl config set-credentials system:node:{{ hostvars[item].ansible_nodename.split('.')[0] }} \
      --client-certificate={{ item }}.pem \
      --client-key={{ item }}-key.pem \
      --embed-certs=true \
      --kubeconfig={{ item }}.kubeconfig

    kubectl config set-context default \
      --cluster=kubernetes-the-hard-way \
      --user=system:node:{{ hostvars[item].ansible_nodename.split('.')[0] }} \
      --kubeconfig={{ item }}.kubeconfig

    kubectl config use-context default --kubeconfig={{ item }}.kubeconfig
  args:
    chdir: /tmp/workers
  with_items: "{{ groups['nodes'] }}"

- name: Generation kube-proxy Kubernetes Configuration File
  shell: |
    kubectl config set-cluster kubernetes-the-hard-way \
        --certificate-authority=ca.pem \
        --embed-certs=true \
        --server=https://{{ hostvars[inventory_hostname].ansible_host }}:6443 \
        --kubeconfig=kube-proxy.kubeconfig

      kubectl config set-credentials system:kube-proxy \
        --client-certificate=kube-proxy.pem \
        --client-key=kube-proxy-key.pem \
        --embed-certs=true \
        --kubeconfig=kube-proxy.kubeconfig

      kubectl config set-context default \
        --cluster=kubernetes-the-hard-way \
        --user=system:kube-proxy \
        --kubeconfig=kube-proxy.kubeconfig

      kubectl config use-context default --kubeconfig=kube-proxy.kubeconfig

  args:
    chdir: /tmp

- name: Generation kube-controller-manager Kubernetes Configuration File
  shell: |
    kubectl config set-cluster kubernetes-the-hard-way \
        --certificate-authority=ca.pem \
        --embed-certs=true \
        --server=https://127.0.0.1:6443 \
        --kubeconfig=kube-controller-manager.kubeconfig

      kubectl config set-credentials system:kube-controller-manager \
        --client-certificate=kube-controller-manager.pem \
        --client-key=kube-controller-manager-key.pem \
        --embed-certs=true \
        --kubeconfig=kube-controller-manager.kubeconfig

      kubectl config set-context default \
        --cluster=kubernetes-the-hard-way \
        --user=system:kube-controller-manager \
        --kubeconfig=kube-controller-manager.kubeconfig

      kubectl config use-context default --kubeconfig=kube-controller-manager.kubeconfig
  args:
    chdir: /tmp

- name: Generation kube-scheduler Kubernetes Configuration File
  shell: |
    kubectl config set-cluster kubernetes-the-hard-way \
        --certificate-authority=ca.pem \
        --embed-certs=true \
        --server=https://127.0.0.1:6443 \
        --kubeconfig=kube-scheduler.kubeconfig

      kubectl config set-credentials system:kube-scheduler \
        --client-certificate=kube-scheduler.pem \
        --client-key=kube-scheduler-key.pem \
        --embed-certs=true \
        --kubeconfig=kube-scheduler.kubeconfig

      kubectl config set-context default \
        --cluster=kubernetes-the-hard-way \
        --user=system:kube-scheduler \
        --kubeconfig=kube-scheduler.kubeconfig

      kubectl config use-context default --kubeconfig=kube-scheduler.kubeconfig
  args:
    chdir: /tmp

- name: Generation admin Kubernetes Configuration File
  shell: |
    kubectl config set-cluster kubernetes-the-hard-way \
        --certificate-authority=ca.pem \
        --embed-certs=true \
        --server=https://127.0.0.1:6443 \
        --kubeconfig=admin.kubeconfig

      kubectl config set-credentials admin \
        --client-certificate=admin.pem \
        --client-key=admin-key.pem \
        --embed-certs=true \
        --kubeconfig=admin.kubeconfig

      kubectl config set-context default \
        --cluster=kubernetes-the-hard-way \
        --user=admin \
        --kubeconfig=admin.kubeconfig

      kubectl config use-context default --kubeconfig=admin.kubeconfig
  args:
    chdir: /tmp

- name: Distribute the Cliens and Server Configuration Files (1/2)
  shell: |
    scp  {{ item }}.kubeconfig ../kube-proxy.kubeconfig {{ item }}:~/
  args:
    chdir: /tmp/workers
  with_items: "{{ groups['nodes'] }}"

- name: Distribute the Cliens and Server Configuration Files (2/2)
  shell: |
    scp admin.kubeconfig kube-controller-manager.kubeconfig \
    kube-scheduler.kubeconfig  {{ item }}:~/
  args:
    chdir: /tmp
  with_items: "{{ groups['masters'] }}"