- name: Copy configuration files
  copy:
    src: "{{ item.name }}"
    dest: "/tmp/{{ item.name }}"
  with_items: "{{ files }}"

- name: Generation Certificate Authority
  shell: cfssl gencert -initca ca-csr.json | cfssljson -bare ca
  args:
    chdir: /tmp

- name: Generation Certificate Admin Client
  shell: |
    cfssl gencert \
      -ca=ca.pem \
      -ca-key=ca-key.pem \
      -config=ca-config.json \
      -profile=kubernetes \
      admin-csr.json | cfssljson -bare admin
  args:
    chdir: /tmp

- include: worker.yaml

- name: Generation Certificate Controller Manager Client
  shell: |
    cfssl gencert \
      -ca=ca.pem \
      -ca-key=ca-key.pem \
      -config=ca-config.json \
      -profile=kubernetes \
      kube-controller-manager-csr.json | cfssljson -bare kube-controller-manager
  args:
    chdir: /tmp

- name: Generation Certificate Kube Proxy Client
  shell: |
    cfssl gencert \
      -ca=ca.pem \
      -ca-key=ca-key.pem \
      -config=ca-config.json \
      -profile=kubernetes \
      kube-proxy-csr.json | cfssljson -bare kube-proxy
  args:
    chdir: /tmp

- name: Generation Certificate Scheduler Client
  shell: |
    cfssl gencert \
      -ca=ca.pem \
      -ca-key=ca-key.pem \
      -config=ca-config.json \
      -profile=kubernetes \
      kube-scheduler-csr.json | cfssljson -bare kube-scheduler
  args:
    chdir: /tmp

- name: Generation API Server Certificate
  shell: |
    cfssl gencert \
      -ca=ca.pem \
      -ca-key=ca-key.pem \
      -config=ca-config.json \
      -hostname={% for node in groups['masters'] %}{{ hostvars[node].ansible_host }},{% endfor %}{{ hostvars[groups['proxy'][0]].ansible_host }},127.0.0.1,{{ kubernetes_hostnames }} \
      -profile=kubernetes \
      kubernetes-csr.json | cfssljson -bare kubernetes
  args:
    chdir: /tmp

- name: Generation Service Account Key Pair
  shell: |
    cfssl gencert \
      -ca=ca.pem \
      -ca-key=ca-key.pem \
      -config=ca-config.json \
      -profile=kubernetes \
      service-account-csr.json | cfssljson -bare service-account
  args:
    chdir: /tmp

- name: Distribute the Cliens and Server Certificates (1/2)
  shell: |
    scp  ../ca.pem {{ item }}-key.pem {{ item }}.pem {{ item }}:~/
  args:
    chdir: /tmp/workers
  with_items: "{{ groups['nodes'] }}"

- name: Distribute the Cliens and Server Certificates (2/2)
  shell: |
    scp ca.pem ca-key.pem kubernetes-key.pem kubernetes.pem \
        service-account-key.pem service-account.pem {{ item }}:~/
  args:
    chdir: /tmp
  with_items: "{{ groups['masters'] }}"