- name: Create dir
  file:
    path: /tmp/workers
    owner: vagrant
    group: vagrant
    state: directory

- name: Generation configuration files
  template:
    src:  worker-csr.json.j2
    dest: "/tmp/workers/{{ item }}-csr.json"
  with_items: "{{ groups['nodes'] }}"

- name: Generation Certificate Kubelet Client
  shell: |
    cfssl gencert \
      -ca=../ca.pem \
      -ca-key=../ca-key.pem \
      -config=../ca-config.json \
      -hostname={{ hostvars[item].ansible_nodename.split('.')[0] }},{{ hostvars[item].ansible_host }} \
      -profile=kubernetes \
      {{ item }}-csr.json | cfssljson -bare {{ item }}
  args:
    chdir: /tmp/workers
  with_items: "{{ groups['nodes'] }}"