- name: Create dir
  file:
    path: /opt/workers
    state: directory

- name: Generation configuration files
  template:
    src:  worker-csr.json.j2
    dest: "/opt/workers/{{ item }}-csr.json"
  with_item: "{{ groups['nodes'] }}"

- name: Generation Certificate Kubelet Client
  shell: |
    cfssl gencert \
      -ca=../ca.pem \
      -ca-key=../ca-key.pem \
      -config=../ca-config.json \
      -hostname="{{ item }}","{{ hostvars[item].ansible_host }}" \
      -profile=kubernetes \
      "{{ item }}"-csr.json | cfssljson -bare "{{ item }}"
  args:
    chdir: /opt/workers
  with_items: "{{ groups['nodes'] }}"