- name: Move tools to bin
  shell: "cp /tmp/{{ item.name }} /usr/local/bin/{{ item.name }}"
  with_items: "{{ tools }}"

- name: Ensure CFSSL
  shell: cfssl version
  become: no

- name: Ensure kubectl
  shell: kubectl version --client
  become: no
