- name: Download tools
  get_url:
    url: "{{ item.url }}"
    dest: "/tmp/{{ item.name}}"
    mode: '0777'
    timeout: 15
  with_items: "{{ tools }}"

- name: Move tools to bin
  shell: "mv /tmp/{{ item.name }} /usr/local/bin/"
  with_items: "{{ tools }}"

- name: Ensure CFSSL
  shell: cfssl version
  become: no

- name: Ensure kubectl
  shell: kubectl version --client
  become: no
