- name: DEPLOYMENT | Install CFSSL
  shell: |
    wget -q --show-progress --https-only --timestamping \
      https://storage.googleapis.com/kubernetes-the-hard-way/cfssl/1.4.1/linux/cfssl \
      https://storage.googleapis.com/kubernetes-the-hard-way/cfssl/1.4.1/linux/cfssljson
    chmod +x cfssl cfssljson
    mv cfssl cfssljson /usr/local/bin/
  args:
    chdir: /tmp

- name: DEPLOYMENT | Ensure CFSSL
  shell: cfssl version

- name: DEPLOYMENT | Install kubectl
  shell: |
    wget https://storage.googleapis.com/kubernetes-release/release/v1.18.6/bin/linux/amd64/kubectl
    chmod +x kubectl
    mv kubectl /usr/local/bin/
  args:
    chdir: /tmp

- name: DEPLOYMENT | Ensure kubectl
  shell: kubectl version --client