- name: Create directory
  shell: sudo mkdir -p /etc/kubernetes/config

- name: Move services
  shell: "mv {{ item }} /usr/local/bin/"
  args:
    chdir: /tmp
  become: yes
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - kubectl

- name: Configure the Kubernetes API Server
  shell: |
    sudo mkdir -p /var/lib/kubernetes/
    sudo mv ca.pem ca-key.pem kubernetes-key.pem kubernetes.pem \
    service-account-key.pem service-account.pem \
    encryption-config.yaml /var/lib/kubernetes/

- name: Generation systemd unit file
  template:
    src: kube-apiserver.service.j2
    dest: /etc/systemd/system/kube-apiserver.service
  become: yes

- name: Move Kubernetes config files
  shell: |
    mv kube-controller-manager.kubeconfig kube-scheduler.kubeconfig \
    /var/lib/kubernetes/
  args:
    chdir: /home/vagrant
  become: yes

- name: Copy systemd unit file
  copy:
    src: "{{ item. name }}"
    dest: "{{ item.path }}"
  with_items: "{{ kube_config_files }}"
  become: yes

- name: Enable Controller Services
  systemd:
    state: started
    enabled: yes
    name: "{{ item }}"
    daemon_reload: yes
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
  become: yes

- name: Configure RBAC permissions
  shell: |
    kubectl apply --kubeconfig admin.kubeconfig -f kube-apiserver-to-kubelet.yaml
    kubectl apply --kubeconfig admin.kubeconfig -f kube-apiserver.yaml

