- name: Ensure new hosts
  hosts: all
  become: yes

  roles:
    - configure

- name: Deploy haproxy
  hosts: proxy
  become: yes

  roles:
    - haproxy

- name: Install tools
  hosts: proxy
  become: yes

  roles:
    - tools

- name: Create cert
  hosts: proxy

  roles:
    - certificate

- name: Configure masters
  hosts: masters

  roles:
    - etcd
    - kubecontrolplane

- name: Configure nodes
  hosts: nodes

  roles:
    - kubeworkplane

- name: Deploy Core DNS
  hosts: master-0

  roles:
    - kubedns

